services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    env_file: .env
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - /volume1/docker/wordpress/caddy/caddy_data:/data
      - /volume1/docker/wordpress/caddy/caddy_config:/config
      - /volume1/docker/wordpress/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /volume1/docker/wordpress/html:/var/www/html

  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: always
    depends_on:
      - db
    volumes:
      - /volume1/docker/wordpress/html:/var/www/html
      - /volume1/docker/wordpress/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file: .env

  db:
    image: mariadb:10.11.6-jammy
    restart: always
    volumes:
      - /volume1/docker/wordpress/mysql:/var/lib/mysql
    env_file: .env

  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    entrypoint: wp
    command: "--info"
    env_file: .env
    volumes:
      - /volume1/docker/wordpress/html:/var/www/html

  #phpmyadmin:
  #  image: bitnami/phpmyadmin:5.2.0-debian-11-r43
  #  ports:
  #    - 8080:8080
  #    - 8443:8443
  #  environment:
  #      DATABASE_HOST: db
  #  restart: always

  #redis:
  #  image: redis:6.2.14
  #  restart: always

  #elastic:
  #  image: elasticsearch:7.17.13
  #  restart: always
  #  environment:
  #    discovery.type: single-node
  #    xpack.security.enabled: false
  #  ports:
  #    - 9200:9200
  #  volumes:
  #    - ./elastic:/usr/share/elasticsearch/data
